#!/usr/bin/env node
// parserail-mcp: an MCP server that exposes ParseRail's capabilities as native
// tools for Claude, Cursor, and any Model Context Protocol client.
//
//   PARSERAIL_API_KEY=ksk_live_... npx parserail-mcp
//
// Register it in your MCP client config (stdio transport). Every tool calls the
// live ParseRail API through the @kynth/api SDK; get a key plus 500 free credits
// every month at https://parserail.thecompound.tech.
//
// ⛔ THE GENERATOR THIS FILE NAMED IS GONE, so this file is hand-maintained now
// (measured 2026-09-19). The header said "AUTO-GENERATED by
// apps/parserail/scripts/generate-clients.ts, do NOT edit by hand. Regenerate with
// `pnpm gen:clients` in apps/parserail". There is no apps/ directory in the
// parserail repo, no gen:clients script anywhere in the estate, and no
// generate-clients.ts on disk; the monorepo layout that sentence describes was
// purged on 2026-09-14. parserail/src/lib/mcp/tools.ts still carries the same dead
// header. Anyone who followed it went looking for a path that does not exist and
// left this file alone, which is why its identity stayed on the retired brand.
//
// The SDK import below is still @kynth/api and the KynthCore / KynthError names
// are that package's own exported API surface, so they are not ours to rename here.
// Renaming the SDK is a separate package with its own installed base.

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import type { ToolAnnotations } from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";
import {
  KynthCore,
  KynthError,
  type ParseInput,
  type ExtractInput,
  type ClassifyInput,
  type SummarizeInput,
  type RedactInput,
  type SentimentInput,
  type ContractInput,
  type ChargebackInput,
  type EnrichInput,
  type InvoiceInput,
  type ReceiptInput,
  type StatementInput,
  type ResumeInput,
  type TablesInput,
  type SplitInput,
  type CompareInput,
  type StructureInput,
  type NormalizeInput,
  type MatchInput,
  type CategorizeInput,
  type DunningInput,
  type PoMatchInput,
  type QuoteInput,
  type FraudFlagInput,
  type ReplyInput,
  type TriageInput,
  type MinutesInput,
  type OutreachInput,
  type ReviewReplyInput,
  type ModerateInput,
  type RewriteInput,
  type ProductCopyInput,
  type DescribeInput,
  type ResearchInput,
  type ScreenInput,
  type TranscribeInput,
  type MemoryInput,
  type ImageInput,
  type SpeakInput,
} from "@kynth/api";

// PARSERAIL_API_KEY IS THE NAME, AND KYNTH_API_KEY STILL WORKS (2026-09-19). The studio is
// Compound Labs and this package is parserail-mcp, but the old variable is set by hand in real
// MCP client configs on other people's machines. Dropping it would break every existing install
// silently, at the one moment a user is least able to debug it, so it is read as a fallback
// rather than removed. New installs are told the new name and only the new name.
const apiKey = process.env.PARSERAIL_API_KEY ?? process.env.KYNTH_API_KEY;
if (!apiKey) {
  console.error(
    "[parserail-mcp] Missing PARSERAIL_API_KEY. Get a key at " +
      "https://parserail.thecompound.tech/dashboard and set it in your MCP client config, " +
      "e.g. { \"env\": { \"PARSERAIL_API_KEY\": \"ksk_live_...\" } }.",
  );
  process.exit(1);
}

const parserail = new KynthCore({
  apiKey,
  baseUrl: process.env.PARSERAIL_BASE_URL || process.env.KYNTH_BASE_URL || undefined,
});

const server = new McpServer({ name: "parserail-mcp", version: "0.5.3" });

/** Wrap an SDK call so any KynthError becomes a clean MCP tool error. */
async function run<T>(fn: () => Promise<T>) {
  try {
    const result = await fn();
    return { content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }] };
  } catch (err) {
    const message =
      err instanceof KynthError
        ? `ParseRail error [${err.code}] (HTTP ${err.status}): ${err.message}`
        : err instanceof Error
          ? err.message
          : "Unknown error";
    return { content: [{ type: "text" as const, text: message }], isError: true };
  }
}

// A document input for the multimodal tools. Provide exactly one source.
const docFields = {
  fileUrl: z.string().url().optional().describe("Public URL to a PDF or image."),
  text: z.string().optional().describe("Raw text, if you already have it."),
  fileBase64: z.string().optional().describe("Base64-encoded file bytes (with fileMimeType)."),
  fileMimeType: z.string().optional().describe("MIME type for fileBase64, e.g. application/pdf."),
};

/** Resolve the doc-input fields into the SDK's DocumentInput union. */
function toDoc(a: { fileUrl?: string; text?: string; fileBase64?: string; fileMimeType?: string }) {
  if (a.fileUrl) return { fileUrl: a.fileUrl };
  if (a.fileBase64 && a.fileMimeType) return { file: { data: a.fileBase64, mimeType: a.fileMimeType } };
  if (a.text) return { text: a.text };
  throw new Error("Provide one of: fileUrl, text, or fileBase64 + fileMimeType.");
}

/**
 * Tool annotations. The Claude Connectors Directory requires every tool to
 * declare a title plus the applicable hints; missing annotations are the single
 * largest cause of submission rejection.
 *
 * Every ParseRail capability tool has the same shape: it calls the hosted API,
 * debits the account's credit wallet, and returns a result. It never mutates the
 * caller's data, and nothing it does is irreversible, but it is NOT read-only,
 * because the wallet balance changes, and NOT idempotent, because a repeat call
 * is charged again.
 */
const CORE_TOOL: ToolAnnotations = {
  readOnlyHint: false,
  destructiveHint: false,
  idempotentHint: false,
  openWorldHint: true,
};

/** Reading your own balance costs nothing and changes nothing. */
const ACCOUNT_TOOL: ToolAnnotations = {
  readOnlyHint: true,
  destructiveHint: false,
  idempotentHint: true,
  openWorldHint: true,
};

server.registerTool(
  "parserail_parse",
  {
    title: "Document parse",
    description: "Any invoice, receipt, EOB, ERA, or COI, PDF or image, into structured, validated JSON. Costs credits from the account wallet.",
    inputSchema: { ...docFields, "docType": z.string().optional().describe("Optional hint, e.g. \"invoice\".") },
    annotations: { title: "Document parse", ...CORE_TOOL },
  },
  (a) => run(() => parserail.parse({ ...toDoc(a), "docType": a["docType"] } as ParseInput)),
);

server.registerTool(
  "parserail_extract",
  {
    title: "Field extraction",
    description: "Pull a field set you define out of any block of text. You name the fields; you get typed values with confidence. Costs credits from the account wallet.",
    inputSchema: { "text": z.string(), "fields": z.array(z.string()).describe("The field names to pull out."), "instructions": z.string().optional().describe("Optional extra guidance.") },
    annotations: { title: "Field extraction", ...CORE_TOOL },
  },
  (a) => run(() => parserail.extract({ "text": a["text"], "fields": a["fields"], "instructions": a["instructions"] } as ExtractInput)),
);

server.registerTool(
  "parserail_classify",
  {
    title: "Classification",
    description: "Route or tag text against your own taxonomy, a label, a confidence, and a one-line rationale. Costs credits from the account wallet.",
    inputSchema: { "text": z.string(), "labels": z.array(z.string()), "multi": z.boolean().optional().describe("Allow multiple labels."), "instructions": z.string().optional() },
    annotations: { title: "Classification", ...CORE_TOOL },
  },
  (a) => run(() => parserail.classify({ "text": a["text"], "labels": a["labels"], "multi": a["multi"], "instructions": a["instructions"] } as ClassifyInput)),
);

server.registerTool(
  "parserail_summarize",
  {
    title: "Summarize",
    description: "A meeting transcript, thread, or report → a tight summary, key points, and extracted action items. Costs credits from the account wallet.",
    inputSchema: { "text": z.string(), "length": z.enum(["brief", "standard", "detailed"]).optional(), "actionItems": z.boolean().optional() },
    annotations: { title: "Summarize", ...CORE_TOOL },
  },
  (a) => run(() => parserail.summarize({ "text": a["text"], "length": a["length"], "actionItems": a["actionItems"] } as SummarizeInput)),
);

server.registerTool(
  "parserail_redact",
  {
    title: "PII redaction",
    description: "Detect and strip names, emails, phones, SSNs, cards, and PHI from text before you store or log it. Costs credits from the account wallet.",
    inputSchema: { "text": z.string(), "types": z.array(z.string()).optional().describe("Entity types to redact; omit for all."), "placeholder": z.string().optional() },
    annotations: { title: "PII redaction", ...CORE_TOOL },
  },
  (a) => run(() => parserail.redact({ "text": a["text"], "types": a["types"], "placeholder": a["placeholder"] } as RedactInput)),
);

server.registerTool(
  "parserail_sentiment",
  {
    title: "Sentiment",
    description: "Turn a review or support message into a sentiment score, per-aspect breakdown, and the themes driving it. Costs credits from the account wallet.",
    inputSchema: { "text": z.string(), "aspects": z.array(z.string()).optional().describe("Optional aspects to break out.") },
    annotations: { title: "Sentiment", ...CORE_TOOL },
  },
  (a) => run(() => parserail.sentiment({ "text": a["text"], "aspects": a["aspects"] } as SentimentInput)),
);

server.registerTool(
  "parserail_contract",
  {
    title: "Contract analysis",
    description: "A contract → parties, effective date, term, renewal, governing law, obligations, and flagged risk clauses. Costs credits from the account wallet.",
    inputSchema: { ...docFields },
    annotations: { title: "Contract analysis", ...CORE_TOOL },
  },
  (a) => run(() => parserail.contract({ ...toDoc(a) } as ContractInput)),
);

server.registerTool(
  "parserail_chargeback",
  {
    title: "Chargeback representment",
    description: "Dispute details → a representment narrative, an evidence checklist, the right reason code, and a win-likelihood. Costs credits from the account wallet.",
    inputSchema: { "reason": z.string().describe("The cardholder's dispute reason."), "transaction": z.object({ "amount": z.number().optional(), "currency": z.string().optional(), "date": z.string().optional(), "descriptor": z.string().optional() }), "evidence": z.array(z.string()).optional(), "context": z.string().optional(), "network": z.enum(["visa", "mastercard", "amex", "discover"]).optional() },
    annotations: { title: "Chargeback representment", ...CORE_TOOL },
  },
  (a) => run(() => parserail.chargeback({ "reason": a["reason"], "transaction": a["transaction"], "evidence": a["evidence"], "context": a["context"], "network": a["network"] } as ChargebackInput)),
);

server.registerTool(
  "parserail_enrich",
  {
    title: "Company enrichment",
    description: "A domain or work email → a structured company profile: name, description, industry, HQ, size, and links. Costs credits from the account wallet.",
    inputSchema: { "domain": z.string().optional(), "email": z.string().optional() },
    annotations: { title: "Company enrichment", ...CORE_TOOL },
  },
  (a) => run(() => parserail.enrich({ "domain": a["domain"], "email": a["email"] } as EnrichInput)),
);

server.registerTool(
  "parserail_invoice",
  {
    title: "Invoice extraction",
    description: "An invoice, PDF, photo, or text, into vendor, dates, PO refs, tax, totals, and clean line items. Costs credits from the account wallet.",
    inputSchema: { ...docFields },
    annotations: { title: "Invoice extraction", ...CORE_TOOL },
  },
  (a) => run(() => parserail.invoice({ ...toDoc(a) } as InvoiceInput)),
);

server.registerTool(
  "parserail_receipt",
  {
    title: "Receipt extraction",
    description: "A receipt into merchant, items, totals, payment method, and an expense category, built for expense flows. Costs credits from the account wallet.",
    inputSchema: { ...docFields },
    annotations: { title: "Receipt extraction", ...CORE_TOOL },
  },
  (a) => run(() => parserail.receipt({ ...toDoc(a) } as ReceiptInput)),
);

server.registerTool(
  "parserail_statement",
  {
    title: "Statement parsing",
    description: "A bank or card statement into the account, the period, balances, and every transaction as a normalized row. Costs credits from the account wallet.",
    inputSchema: { ...docFields },
    annotations: { title: "Statement parsing", ...CORE_TOOL },
  },
  (a) => run(() => parserail.statement({ ...toDoc(a) } as StatementInput)),
);

server.registerTool(
  "parserail_resume",
  {
    title: "Resume parsing",
    description: "A resume or CV into a structured candidate profile: contact, skills, experience, education, and links. Costs credits from the account wallet.",
    inputSchema: { ...docFields },
    annotations: { title: "Resume parsing", ...CORE_TOOL },
  },
  (a) => run(() => parserail.resume({ ...toDoc(a) } as ResumeInput)),
);

server.registerTool(
  "parserail_tables",
  {
    title: "Table extraction",
    description: "Every table in a document, even scanned, as clean headers and rows, ready for your spreadsheet or DB. Costs credits from the account wallet.",
    inputSchema: { ...docFields },
    annotations: { title: "Table extraction", ...CORE_TOOL },
  },
  (a) => run(() => parserail.tables({ ...toDoc(a) } as TablesInput)),
);

server.registerTool(
  "parserail_split",
  {
    title: "Document splitting",
    description: "A multi-document scan bundle classified and split: what each document is, where it starts and ends, and a summary. Costs credits from the account wallet.",
    inputSchema: { ...docFields },
    annotations: { title: "Document splitting", ...CORE_TOOL },
  },
  (a) => run(() => parserail.split({ ...toDoc(a) } as SplitInput)),
);

server.registerTool(
  "parserail_compare",
  {
    title: "Document comparison",
    description: "Two versions of a contract or document → every material change, what it means, and the risk it carries. Costs credits from the account wallet.",
    inputSchema: { "a": z.object({ "file": z.object({ "data": z.string().describe("Base64-encoded file bytes."), "mimeType": z.string() }).optional().describe("Inline document."), "fileUrl": z.string().optional().describe("Public URL to a PDF or image."), "text": z.string().optional().describe("Raw text, if you already have it.") }).describe("The earlier version (file, fileUrl, or text)."), "b": z.object({ "file": z.object({ "data": z.string().describe("Base64-encoded file bytes."), "mimeType": z.string() }).optional().describe("Inline document."), "fileUrl": z.string().optional().describe("Public URL to a PDF or image."), "text": z.string().optional().describe("Raw text, if you already have it.") }).describe("The later version (file, fileUrl, or text).") },
    annotations: { title: "Document comparison", ...CORE_TOOL },
  },
  (a) => run(() => parserail.compare({ "a": a["a"], "b": a["b"] } as CompareInput)),
);

server.registerTool(
  "parserail_structure",
  {
    title: "Structure to your schema",
    description: "Any messy input, text, HTML, an email, plus YOUR JSON schema → output shaped to it, validated against your required fields and property types, with an automatic corrective retry and a `valid` flag. Costs credits from the account wallet.",
    inputSchema: { "input": z.string().describe("Any messy input, text, HTML, an email, a JSON blob."), "schema": z.object({  }).describe("The JSON Schema the output must conform to."), "instructions": z.string().optional().describe("Optional extra guidance.") },
    annotations: { title: "Structure to your schema", ...CORE_TOOL },
  },
  (a) => run(() => parserail.structure({ "input": a["input"], "schema": a["schema"], "instructions": a["instructions"] } as StructureInput)),
);

server.registerTool(
  "parserail_normalize",
  {
    title: "Record normalization",
    description: "A batch of messy records → clean canonical rows, with a change log of every fix (casing, formats, dedup-ready values). Costs credits from the account wallet.",
    inputSchema: { "records": z.array(z.object({  })).describe("The messy records."), "fields": z.array(z.string()).optional().describe("Canonical field names to normalize into; omit to keep the input's fields."), "instructions": z.string().optional().describe("House rules, e.g. \"US phone format, uppercase state codes\".") },
    annotations: { title: "Record normalization", ...CORE_TOOL },
  },
  (a) => run(() => parserail.normalize({ "records": a["records"], "fields": a["fields"], "instructions": a["instructions"] } as NormalizeInput)),
);

server.registerTool(
  "parserail_match",
  {
    title: "Entity matching",
    description: "Two record sets → which rows are the same real-world thing, with confidence and reasoning. Fuzzy names, typos, aliases handled. Costs credits from the account wallet.",
    inputSchema: { "a": z.array(z.object({  })).describe("First record set."), "b": z.array(z.object({  })).describe("Second record set."), "keys": z.array(z.string()).optional().describe("Fields that most identify an entity, e.g. [\"name\",\"email\"].") },
    annotations: { title: "Entity matching", ...CORE_TOOL },
  },
  (a) => run(() => parserail.match({ "a": a["a"], "b": a["b"], "keys": a["keys"] } as MatchInput)),
);

server.registerTool(
  "parserail_categorize",
  {
    title: "Batch categorization",
    description: "Up to a hundred items against your taxonomy in one call, products, transactions, tickets, each with a confidence. Costs credits from the account wallet.",
    inputSchema: { "items": z.array(z.string()).describe("The things to categorize."), "taxonomy": z.array(z.string()).describe("Your categories."), "multi": z.boolean().optional().describe("Allow multiple categories per item."), "instructions": z.string().optional() },
    annotations: { title: "Batch categorization", ...CORE_TOOL },
  },
  (a) => run(() => parserail.categorize({ "items": a["items"], "taxonomy": a["taxonomy"], "multi": a["multi"], "instructions": a["instructions"] } as CategorizeInput)),
);

server.registerTool(
  "parserail_dunning",
  {
    title: "Collections sequence",
    description: "An overdue invoice → a ready-to-send collection sequence, escalating at the right pace and tone for how late it is. Costs credits from the account wallet.",
    inputSchema: { "invoice": z.object({ "number": z.string().optional(), "amount": z.number(), "currency": z.string().optional(), "dueDate": z.string().optional().describe("YYYY-MM-DD."), "daysOverdue": z.number().int().optional() }), "customer": z.object({ "name": z.string(), "history": z.string().optional().describe("Payment history / relationship context.") }), "tone": z.enum(["friendly", "firm", "final"]).optional().describe("Where to start the escalation."), "channel": z.enum(["email", "sms"]).optional(), "steps": z.number().int().optional() },
    annotations: { title: "Collections sequence", ...CORE_TOOL },
  },
  (a) => run(() => parserail.dunning({ "invoice": a["invoice"], "customer": a["customer"], "tone": a["tone"], "channel": a["channel"], "steps": a["steps"] } as DunningInput)),
);

server.registerTool(
  "parserail_po_match",
  {
    title: "3-way match",
    description: "Invoice vs purchase order vs receipt → matched, partial, or mismatched, with every discrepancy flagged and sized. Costs credits from the account wallet.",
    inputSchema: { "invoice": z.string().describe("The invoice, structured JSON (e.g. /v1/invoice output) or raw text."), "purchaseOrder": z.string().describe("The PO, structured JSON or raw text."), "receipt": z.string().optional().describe("Optional goods receipt / delivery note for a 3-way match."), "tolerancePct": z.number().optional().describe("Price variance tolerance in percent (default 2).") },
    annotations: { title: "3-way match", ...CORE_TOOL },
  },
  (a) => run(() => parserail.poMatch({ "invoice": a["invoice"], "purchaseOrder": a["purchaseOrder"], "receipt": a["receipt"], "tolerancePct": a["tolerancePct"] } as PoMatchInput)),
);

server.registerTool(
  "parserail_quote",
  {
    title: "Quote builder",
    description: "A job description plus your rates → an itemized, professional quote with assumptions and scope notes spelled out. Costs credits from the account wallet.",
    inputSchema: { "job": z.string().describe("What the customer needs, in plain words."), "rates": z.string().optional().describe("Your rate card / pricing rules, any format."), "pastQuotes": z.string().optional().describe("Optional examples of quotes you've sent."), "currency": z.string().optional() },
    annotations: { title: "Quote builder", ...CORE_TOOL },
  },
  (a) => run(() => parserail.quote({ "job": a["job"], "rates": a["rates"], "pastQuotes": a["pastQuotes"], "currency": a["currency"] } as QuoteInput)),
);

server.registerTool(
  "parserail_fraud_flag",
  {
    title: "Fraud triage",
    description: "An order or transaction in context → a risk score, the signals driving it, and the checks worth running before you ship. Costs credits from the account wallet.",
    inputSchema: { "order": z.object({  }).describe("The order/transaction: amount, email, addresses, IP, device, history, whatever you have."), "context": z.string().optional().describe("Store context: typical order size, known patterns.") },
    annotations: { title: "Fraud triage", ...CORE_TOOL },
  },
  (a) => run(() => parserail.fraudFlag({ "order": a["order"], "context": a["context"] } as FraudFlagInput)),
);

server.registerTool(
  "parserail_reply",
  {
    title: "Reply drafting",
    description: "A customer thread plus your context → a ready-to-send reply in the right tone, with an internal note for the agent. Costs credits from the account wallet.",
    inputSchema: { "thread": z.string().describe("The email/ticket thread, newest last."), "context": z.string().optional().describe("Policies, KB extracts, account facts the reply may use."), "tone": z.enum(["professional", "friendly", "apologetic", "firm"]).optional(), "goal": z.string().optional().describe("What the reply should achieve, e.g. \"offer refund, keep them\"."), "senderName": z.string().optional().describe("Sign-off name.") },
    annotations: { title: "Reply drafting", ...CORE_TOOL },
  },
  (a) => run(() => parserail.reply({ "thread": a["thread"], "context": a["context"], "tone": a["tone"], "goal": a["goal"], "senderName": a["senderName"] } as ReplyInput)),
);

server.registerTool(
  "parserail_triage",
  {
    title: "Ticket triage",
    description: "A support ticket → priority, category, the team it belongs to, sentiment, SLA risk, and a suggested first response. Costs credits from the account wallet.",
    inputSchema: { "ticket": z.string().describe("The ticket text (subject + body)."), "categories": z.array(z.string()).optional().describe("Your category set; omit for sensible defaults."), "teams": z.array(z.string()).optional().describe("Routable teams.") },
    annotations: { title: "Ticket triage", ...CORE_TOOL },
  },
  (a) => run(() => parserail.triage({ "ticket": a["ticket"], "categories": a["categories"], "teams": a["teams"] } as TriageInput)),
);

server.registerTool(
  "parserail_minutes",
  {
    title: "Meeting minutes",
    description: "A meeting transcript → clean minutes: summary, decisions made, action items with owners, and open questions. Costs credits from the account wallet.",
    inputSchema: { "transcript": z.string().describe("The meeting transcript."), "attendees": z.array(z.string()).optional() },
    annotations: { title: "Meeting minutes", ...CORE_TOOL },
  },
  (a) => run(() => parserail.minutes({ "transcript": a["transcript"], "attendees": a["attendees"] } as MinutesInput)),
);

server.registerTool(
  "parserail_outreach",
  {
    title: "Outreach sequence",
    description: "An enriched lead plus what you sell → a personalized outreach sequence that references what actually makes them a fit. Costs credits from the account wallet.",
    inputSchema: { "lead": z.string().describe("Who you're writing to, an enriched profile (e.g. /v1/enrich output) or notes."), "product": z.string().describe("What you sell and the value proposition."), "sender": z.object({ "name": z.string().optional(), "role": z.string().optional(), "company": z.string().optional() }).optional(), "channel": z.enum(["email", "linkedin"]).optional(), "steps": z.number().int().optional() },
    annotations: { title: "Outreach sequence", ...CORE_TOOL },
  },
  (a) => run(() => parserail.outreach({ "lead": a["lead"], "product": a["product"], "sender": a["sender"], "channel": a["channel"], "steps": a["steps"] } as OutreachInput)),
);

server.registerTool(
  "parserail_review_reply",
  {
    title: "Review response",
    description: "A customer review → a brand-safe public response, the issues to log, and whether it needs human escalation. Costs credits from the account wallet.",
    inputSchema: { "review": z.string().describe("The customer review text."), "rating": z.number().optional().describe("Star rating if known."), "business": z.object({ "name": z.string().optional(), "voice": z.string().optional().describe("Brand voice notes.") }).optional(), "resolution": z.string().optional().describe("What you can offer, e.g. \"replacement or refund\".") },
    annotations: { title: "Review response", ...CORE_TOOL },
  },
  (a) => run(() => parserail.reviewReply({ "review": a["review"], "rating": a["rating"], "business": a["business"], "resolution": a["resolution"] } as ReviewReplyInput)),
);

server.registerTool(
  "parserail_moderate",
  {
    title: "Content moderation",
    description: "Text or an image against YOUR policy → allow, review, or block, with the categories and excerpts that drove the call. Costs credits from the account wallet.",
    inputSchema: { "text": z.string().optional(), "image": z.object({ "data": z.string().describe("Base64."), "mimeType": z.string() }).optional(), "imageUrl": z.string().optional(), "policy": z.string().optional().describe("YOUR rules, plain words, e.g. \"no medical claims, no competitor names\". Adds to the safety baseline.") },
    annotations: { title: "Content moderation", ...CORE_TOOL },
  },
  (a) => run(() => parserail.moderate({ "text": a["text"], "image": a["image"], "imageUrl": a["imageUrl"], "policy": a["policy"] } as ModerateInput)),
);

server.registerTool(
  "parserail_rewrite",
  {
    title: "Brand-voice rewrite",
    description: "Any copy → your brand voice. Describe the voice or paste a sample; get the rewrite and what changed. Costs credits from the account wallet.",
    inputSchema: { "text": z.string(), "voice": z.string().optional().describe("Describe the voice or paste a sample of it."), "goal": z.string().optional().describe("e.g. \"tighter, more confident\"."), "audience": z.string().optional(), "length": z.enum(["shorter", "same", "longer"]).optional() },
    annotations: { title: "Brand-voice rewrite", ...CORE_TOOL },
  },
  (a) => run(() => parserail.rewrite({ "text": a["text"], "voice": a["voice"], "goal": a["goal"], "audience": a["audience"], "length": a["length"] } as RewriteInput)),
);

server.registerTool(
  "parserail_product_copy",
  {
    title: "Product copy",
    description: "Specs and an audience → listing-ready titles, bullets, a description, and SEO keywords, per channel. Costs credits from the account wallet.",
    inputSchema: { "product": z.object({ "name": z.string(), "features": z.string().optional().describe("Specs / features, any format."), "audience": z.string().optional(), "keywords": z.array(z.string()).optional() }), "channel": z.enum(["amazon", "shopify", "generic"]).optional() },
    annotations: { title: "Product copy", ...CORE_TOOL },
  },
  (a) => run(() => parserail.productCopy({ "product": a["product"], "channel": a["channel"] } as ProductCopyInput)),
);

server.registerTool(
  "parserail_describe",
  {
    title: "Image description",
    description: "An image → accessible alt text, a caption, tags, and any text found inside it. Accessibility and catalogs in one call. Costs credits from the account wallet.",
    inputSchema: { "image": z.object({ "data": z.string().describe("Base64."), "mimeType": z.string() }).optional(), "imageUrl": z.string().optional(), "purpose": z.enum(["alt", "caption", "product", "detailed"]).optional() },
    annotations: { title: "Image description", ...CORE_TOOL },
  },
  (a) => run(() => parserail.describe({ "image": a["image"], "imageUrl": a["imageUrl"], "purpose": a["purpose"] } as DescribeInput)),
);

server.registerTool(
  "parserail_research",
  {
    title: "Research brief",
    description: "A company or topic → a multi-source, citation-backed brief: what it is, what changed lately, and what matters. Real web work. Costs credits from the account wallet.",
    inputSchema: { "query": z.string().describe("The company, topic, or question to research."), "focus": z.string().optional().describe("What matters to you, e.g. \"pricing changes and funding\"."), "depth": z.enum(["standard", "deep"]).optional().describe("deep reads more sources.") },
    annotations: { title: "Research brief", ...CORE_TOOL },
  },
  (a) => run(() => parserail.research({ "query": a["query"], "focus": a["focus"], "depth": a["depth"] } as ResearchInput)),
);

server.registerTool(
  "parserail_screen",
  {
    title: "Lead screening",
    description: "A lead plus your ICP criteria → a web-grounded qualification verdict with the evidence for and against. Costs credits from the account wallet.",
    inputSchema: { "lead": z.string().describe("Company domain, name, or a pasted profile."), "criteria": z.string().describe("Your ICP, plain words, e.g. \"B2B SaaS, 20-200 employees, US, sells to finance teams\".") },
    annotations: { title: "Lead screening", ...CORE_TOOL },
  },
  (a) => run(() => parserail.screen({ "lead": a["lead"], "criteria": a["criteria"] } as ScreenInput)),
);

server.registerTool(
  "parserail_transcribe",
  {
    title: "Transcription",
    description: "An audio recording → accurate text with speakers and paragraph timestamps. Meetings, calls, voice notes. Costs credits from the account wallet.",
    inputSchema: { "audio": z.object({ "data": z.string().describe("Base64 audio."), "mimeType": z.string() }).optional(), "audioUrl": z.string().optional(), "diarize": z.boolean().optional().describe("Label speakers."), "language": z.string().optional().describe("BCP-47 hint, e.g. \"en\".") },
    annotations: { title: "Transcription", ...CORE_TOOL },
  },
  (a) => run(() => parserail.transcribe({ "audio": a["audio"], "audioUrl": a["audioUrl"], "diarize": a["diarize"], "language": a["language"] } as TranscribeInput)),
);

server.registerTool(
  "parserail_memory",
  {
    title: "Agent memory",
    description: "Store, search, and forget memories for your agents, semantic recall on your own namespace, no vector DB to run. Costs credits from the account wallet.",
    inputSchema: { "op": z.enum(["store", "search", "forget"]).describe("The operation."), "namespace": z.string().optional().describe("Your partition key, an agent id, a user id. Defaults to \"default\"."), "content": z.string().optional().describe("store: the memory text."), "metadata": z.object({  }).optional().describe("store: attached metadata, returned on recall."), "query": z.string().optional().describe("search: what to recall."), "limit": z.number().int().optional().describe("search: max results."), "id": z.string().optional().describe("forget: the memory id (or omit with namespace to wipe it).") },
    annotations: { title: "Agent memory", ...CORE_TOOL },
  },
  (a) => run(() => parserail.memory({ "op": a["op"], "namespace": a["namespace"], "content": a["content"], "metadata": a["metadata"], "query": a["query"], "limit": a["limit"], "id": a["id"] } as MemoryInput)),
);

server.registerTool(
  "parserail_image",
  {
    title: "Image generation",
    description: "A prompt → a production-ready image. Marketing visuals, product scenes, and consistent brand imagery. Costs credits from the account wallet.",
    inputSchema: { "prompt": z.string().describe("What to generate."), "style": z.string().optional().describe("Style notes, e.g. \"editorial photography, warm light\"."), "aspectRatio": z.enum(["1:1", "16:9", "9:16", "4:3", "3:4"]).optional() },
    annotations: { title: "Image generation", ...CORE_TOOL },
  },
  (a) => run(() => parserail.image({ "prompt": a["prompt"], "style": a["style"], "aspectRatio": a["aspectRatio"] } as ImageInput)),
);

server.registerTool(
  "parserail_speak",
  {
    title: "Text to speech",
    description: "Text → natural speech audio, ready to embed. Voice notes, IVR lines, narration. Costs credits from the account wallet.",
    inputSchema: { "text": z.string(), "voice": z.string().optional().describe("Voice name; omit for the default narrator."), "pace": z.enum(["slow", "normal", "fast"]).optional() },
    annotations: { title: "Text to speech", ...CORE_TOOL },
  },
  (a) => run(() => parserail.speak({ "text": a["text"], "voice": a["voice"], "pace": a["pace"] } as SpeakInput)),
);

server.registerTool(
  "parserail_account",
  {
    title: "Account balance",
    description: "Get the authenticated account's credit balance.",
    inputSchema: {},
    annotations: { title: "Account balance", ...ACCOUNT_TOOL },
  },
  () => run(() => parserail.account()),
);

// Free public dataset, no key, no credits. Served from api.parserail.studio.
server.registerTool(
  "parserail_late_fee_rules",
  {
    title: "US late-fee ceilings by state",
    description:
      "Look up the maximum late-fee/interest rate a US state allows on a commercial (B2B) invoice, with the statute cite. Statute-verified conservative safe floors. Free, costs no credits.",
    inputSchema: {
      state: z
        .string()
        .length(2)
        .optional()
        .describe("Two-letter USPS state code (e.g. CA). Omit for all 51 rows."),
    },
    annotations: { title: "US late-fee ceilings by state", ...ACCOUNT_TOOL },
  },
  (a) =>
    run(async () => {
      const res = await fetch("https://api.parserail.studio/public/late-fee-rules");
      if (!res.ok) throw new Error("Dataset fetch failed (HTTP " + res.status + ")");
      const data = (await res.json()) as {
        verifiedAt: string;
        rules: { code: string }[];
      };
      if (a.state) {
        const rule = data.rules.find(
          (r) => r.code.toUpperCase() === String(a.state).toUpperCase(),
        );
        if (!rule) throw new Error("Unknown state code: " + a.state);
        return { verifiedAt: data.verifiedAt, rule };
      }
      return data;
    }),
);

const transport = new StdioServerTransport();
await server.connect(transport);
console.error("[kynth-mcp] ParseRail MCP server running on stdio.");
